services: 
  http_service: 
    build:
     context: servers/demo_http
    ports: 
      - '8000:80'
  ftp_service:
    build:
      context: servers/demo_ftp
    ports:
      - '21:21'
      - "60000-60010:60000-60010" # passive port for file transfer (10 connections max)
    volumes:
      - ftp_service_volume:/home/files

  api:
    build:
      context: backend/NetboardApi
      target: final
    ports:
      - "5043:8080"
    container_name: netboard_api
    hostname: netboard_api_host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # todo: change to production
      - ConnectionStrings__DefaultConnection=${POSTGRES_CONNECTION_STRING}
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: netboard_db
    hostname: netboard_db_host
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - netboard_data:/var/lib/postgresql/data 

volumes:
  ftp_service_volume:
  netboard_data: